@php($paymentMethod = $paymentMethod ?? null)
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Nama metode <span class="text-danger">*</span></label><input name="name" value="{{ old('name',$paymentMethod?->name) }}" class="form-control @error('name') is-invalid @enderror" placeholder="Cash" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Kode</label><input name="code" value="{{ old('code',$paymentMethod?->code) }}" class="form-control @error('code') is-invalid @enderror" placeholder="Otomatis dari nama">@error('code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Jenis <span class="text-danger">*</span></label><select name="type" class="form-select" required>@foreach(['cash'=>'Cash','debit'=>'Debit','qris'=>'QRIS','bank_transfer'=>'Bank Transfer','card'=>'Kartu','ewallet'=>'E-Wallet','virtual_account'=>'Virtual Account','gateway'=>'Gateway','other'=>'Lainnya'] as $value=>$label)<option value="{{ $value }}" @selected(old('type',$paymentMethod?->type ?? 'cash')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Kanal <span class="text-danger">*</span></label><select name="channel" class="form-select" id="payment-channel" required><option value="manual" @selected(old('channel',$paymentMethod?->channel ?? 'manual')==='manual')>Manual / Offline</option><option value="midtrans" @selected(old('channel',$paymentMethod?->channel)==='midtrans')>Midtrans / Online</option></select></div>
    <div class="col-md-4"><label class="form-label">Urutan</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$paymentMethod?->sort_order ?? 0) }}" class="form-control"></div>
    <div class="col-12" id="gateway-code"><label class="form-label">Kode metode gateway</label><input name="gateway_method_code" value="{{ old('gateway_method_code',$paymentMethod?->gateway_method_code) }}" class="form-control" placeholder="Contoh: bank_transfer atau gopay"><small class="text-muted">Opsional; disesuaikan dengan payment type Midtrans.</small></div>
    <div class="col-12"><label class="form-label">Instruksi pembayaran</label><textarea name="instructions" rows="4" class="form-control">{{ old('instructions',$paymentMethod?->instructions) }}</textarea></div>
    <div class="col-12"><div class="alert alert-light-info text-info"><i class="ti ti-shield-lock me-2"></i>Status online ditentukan otomatis dari kanal. Server Key Midtrans tidak pernah disimpan pada metode atau dikirim ke browser.</div></div>
    <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active',$paymentMethod?->is_active ?? true))><label class="form-check-label" for="is_active">Metode pembayaran aktif</label></div></div>
</div>
