@php($service = $hotelService ?? null)
<div class="row g-3">
    <div class="col-md-5"><label class="form-label">Nama layanan *</label><input name="name" value="{{ old('name',$service?->name) }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Kode</label><input name="code" value="{{ old('code',$service?->code) }}" class="form-control" placeholder="Otomatis"></div>
    <div class="col-md-4"><label class="form-label">Kategori</label><select name="category" class="form-select">@foreach(['massage'=>'Massage','spa'=>'Spa','laundry'=>'Laundry','transport'=>'Transport','extra_bed'=>'Extra Bed','other'=>'Lainnya'] as $value=>$label)<option value="{{ $value }}" @selected(old('category',$service?->category ?? 'other')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Harga *</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" name="price" value="{{ old('price',$service?->price) }}" class="form-control" required></div></div>
    <div class="col-md-3"><label class="form-label">Satuan harga</label><select name="price_unit" class="form-select">@foreach(['per_order'=>'Per pesanan','per_hour'=>'Per jam','per_item'=>'Per item','per_kg'=>'Per kg'] as $value=>$label)<option value="{{ $value }}" @selected(old('price_unit',$service?->price_unit ?? 'per_order')===$value)>{{ $label }}</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label">Durasi</label><div class="input-group"><input type="number" min="1" name="duration_minutes" value="{{ old('duration_minutes',$service?->duration_minutes) }}" class="form-control"><span class="input-group-text">menit</span></div></div>
    <div class="col-md-2"><label class="form-label">Urutan</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$service?->sort_order ?? 0) }}" class="form-control"></div>
    <div class="col-md-8"><label class="form-label">Deskripsi</label><textarea name="description" rows="4" class="form-control">{{ old('description',$service?->description) }}</textarea></div>
    <div class="col-md-4"><label class="form-label">Foto</label><input type="file" name="image" accept=".jpg,.jpeg,.png,.webp" class="form-control">@if($service?->image_path)<img src="{{ Storage::url($service->image_path) }}" class="rounded mt-2 w-100" style="height:100px;object-fit:cover" alt="{{ $service->name }}">@endif</div>
    <div class="col-12 d-flex flex-wrap gap-4">@foreach(['requires_schedule'=>'Wajib memilih jadwal','is_available'=>'Tersedia dipesan','is_active'=>'Aktif'] as $field=>$label)<div class="form-check form-switch"><input type="hidden" name="{{ $field }}" value="0"><input class="form-check-input" type="checkbox" name="{{ $field }}" value="1" id="{{ $field }}" @checked(old($field,$service?->{$field} ?? ($field!=='requires_schedule')))><label class="form-check-label" for="{{ $field }}">{{ $label }}</label></div>@endforeach</div>
</div>
