@extends('layouts.guest')
@section('title', 'Layanan Kamar '.$access->room->room_number)
@section('content')
    <section class="auth-section"><div class="container"><div class="d-flex flex-wrap align-items-center justify-content-between mb-5"><div><p class="text-uppercase mb-1" style="letter-spacing:2px;color:#dfa974;font-weight:700">In-Stay Portal</p><h2>Kamar {{ $access->room->room_number }}</h2><p class="text-muted mb-0">Selamat datang, {{ $access->stay->guest_name }}.</p></div><form method="POST" action="{{ route('room-service.logout') }}" data-confirm="Anda perlu memindai QR dan memverifikasi nomor telepon lagi untuk masuk." data-confirm-title="Tutup sesi layanan kamar?">@csrf<button class="btn btn-outline-secondary">Keluar dari portal</button></form></div>
        @php($services=[['Makanan & Minuman','Pesan menu langsung ke kamar.','fa-cutlery',route('room-service.food.index'),'Buka menu'],['Pesanan F&B Saya','Pantau status pesanan makanan dan minuman.','fa-list-alt',route('room-service.food.orders'),'Lihat pesanan'],['Layanan Hotel','Massage, spa, laundry, transport, dan lainnya.','fa-bell',route('room-service.services.index'),'Pilih layanan'],['Pesanan Layanan','Pantau jadwal dan proses layanan hotel.','fa-calendar-check-o',route('room-service.services.orders'),'Lihat layanan'],['Housekeeping & Bantuan','Minta pembersihan, amenity, atau bantuan Receptionist.','fa-comments',route('room-service.requests.index'),'Buat permintaan'],['Tagihan Berjalan','Lihat folio, pembayaran, dan saldo kamar.','fa-file-text-o',route('room-service.bill.show'),'Lihat tagihan']])
        <div class="row">@foreach($services as [$title,$description,$icon,$url,$label])<div class="col-md-6 col-lg-4 mb-4"><div class="card dashboard-card h-100"><div class="card-body p-4"><i class="fa {{ $icon }} mb-3" style="font-size:30px;color:#dfa974"></i><h4>{{ $title }}</h4><p class="text-muted mb-3">{{ $description }}</p>@if($url)<a href="{{ $url }}" class="small text-uppercase" style="color:#dfa974;font-weight:700;letter-spacing:1px">{{ $label }} <i class="fa fa-arrow-right"></i></a>@else<span class="small text-uppercase" style="color:#dfa974;font-weight:700;letter-spacing:1px">{{ $label }}</span>@endif</div></div></div>@endforeach</div>
        <div class="alert alert-light border"><strong>Keamanan akses:</strong> sesi ini terikat ke active stay Kamar {{ $access->room->room_number }} dan otomatis tidak berlaku setelah dicabut atau check-out.</div>
    </div></section>
@endsection
