@php
    $promotion = $promotion ?? null;
    $selectedRoomTypes = old('room_types',$promotion ? $promotion->roomTypes->pluck('id')->all() : []);
@endphp
<div class="row g-3">
    <div class="col-md-4"><label class="form-label">Kode promosi <span class="text-danger">*</span></label><input name="code" value="{{ old('code',$promotion?->code) }}" class="form-control @error('code') is-invalid @enderror" placeholder="STAY20" required>@error('code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-8"><label class="form-label">Nama promosi <span class="text-danger">*</span></label><input name="name" value="{{ old('name',$promotion?->name) }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label">Deskripsi</label><textarea name="description" rows="3" class="form-control">{{ old('description',$promotion?->description) }}</textarea></div>
    <div class="col-md-3"><label class="form-label">Jenis diskon</label><select name="discount_type" class="form-select"><option value="percent" @selected(old('discount_type',$promotion?->discount_type ?? 'percent')==='percent')>Persentase</option><option value="fixed" @selected(old('discount_type',$promotion?->discount_type)==='fixed')>Nominal tetap</option></select></div>
    <div class="col-md-3"><label class="form-label">Nilai diskon</label><input type="number" min="0.01" step="0.01" name="discount_value" value="{{ old('discount_value',$promotion?->discount_value) }}" class="form-control @error('discount_value') is-invalid @enderror" required>@error('discount_value')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Maksimal diskon</label><input type="number" min="0" name="max_discount_amount" value="{{ old('max_discount_amount',$promotion?->max_discount_amount) }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">Minimal transaksi</label><input type="number" min="0" name="minimum_transaction" value="{{ old('minimum_transaction',$promotion?->minimum_transaction ?? 0) }}" class="form-control" required></div>
    <div class="col-md-3"><label class="form-label">Mulai</label><input type="datetime-local" name="starts_at" value="{{ old('starts_at',$promotion?->starts_at?->format('Y-m-d\TH:i')) }}" class="form-control"></div>
    <div class="col-md-3"><label class="form-label">Berakhir</label><input type="datetime-local" name="ends_at" value="{{ old('ends_at',$promotion?->ends_at?->format('Y-m-d\TH:i')) }}" class="form-control @error('ends_at') is-invalid @enderror">@error('ends_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Kuota total</label><input type="number" min="1" name="usage_quota" value="{{ old('usage_quota',$promotion?->usage_quota) }}" class="form-control" placeholder="Tanpa batas"></div>
    <div class="col-md-3"><label class="form-label">Maks. per tamu</label><input type="number" min="1" name="max_usage_per_guest" value="{{ old('max_usage_per_guest',$promotion?->max_usage_per_guest) }}" class="form-control"></div>
    <div class="col-12"><label class="form-label">Berlaku untuk tipe kamar</label><div class="row g-2">@foreach($roomTypes as $roomType)<div class="col-md-4"><div class="form-check border rounded p-3 ps-5"><input class="form-check-input" type="checkbox" name="room_types[]" value="{{ $roomType->id }}" id="rt-{{ $roomType->id }}" @checked(in_array($roomType->id,$selectedRoomTypes))><label class="form-check-label" for="rt-{{ $roomType->id }}">{{ $roomType->name }}</label></div></div>@endforeach</div><small class="text-muted">Kosongkan untuk berlaku pada semua tipe kamar.</small></div>
    <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active',$promotion?->is_active ?? true))><label class="form-check-label" for="is_active">Promosi aktif</label></div></div>
</div>
