@php($facility = $facility ?? null)
<div class="row g-3">
    <div class="col-md-7"><label class="form-label">Nama fasilitas <span class="text-danger">*</span></label><input name="name" value="{{ old('name', $facility?->name) }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-5"><label class="form-label">Slug</label><input name="slug" value="{{ old('slug', $facility?->slug) }}" class="form-control @error('slug') is-invalid @enderror" placeholder="Otomatis dari nama">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Cakupan <span class="text-danger">*</span></label><select name="scope" class="form-select @error('scope') is-invalid @enderror" required>@foreach(['room' => 'Kamar', 'hotel' => 'Hotel', 'both' => 'Kamar & Hotel'] as $value => $label)<option value="{{ $value }}" @selected(old('scope', $facility?->scope ?? 'room') === $value)>{{ $label }}</option>@endforeach</select>@error('scope')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Ikon Tabler</label><input name="icon" value="{{ old('icon', $facility?->icon) }}" class="form-control" placeholder="Contoh: ti-wifi"></div>
    <div class="col-md-4"><label class="form-label">Urutan</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $facility?->sort_order ?? 0) }}" class="form-control"></div>
    <div class="col-12"><label class="form-label">Deskripsi</label><textarea name="description" rows="4" class="form-control @error('description') is-invalid @enderror">{{ old('description', $facility?->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active', $facility?->is_active ?? true))><label class="form-check-label" for="is_active">Fasilitas aktif dan dapat ditampilkan</label></div></div>
</div>
