@extends('layouts.guest')
@section('title', 'Pesan Makanan & Minuman')
@push('styles')
<style>.menu-card{border:0;box-shadow:0 8px 24px rgba(25,25,26,.08);height:100%}.menu-card img{height:180px;object-fit:cover;width:100%}.quantity-control{max-width:90px}</style>
@endpush
@section('content')
<section class="auth-section"><div class="container">
    <div class="d-flex flex-wrap justify-content-between align-items-center mb-5"><div><p class="text-uppercase mb-1" style="letter-spacing:2px;color:#dfa974;font-weight:700">Room {{ $access->room->room_number }}</p><h2>Makanan & Minuman</h2><p class="text-muted">Pilih menu; harga yang tercatat saat pemesanan akan dipertahankan.</p></div><div><a href="{{ route('room-service.food.orders') }}" class="btn btn-outline-secondary mr-2">Pesanan Saya</a><a href="{{ route('room-service.home') }}" class="btn btn-outline-secondary">Portal</a></div></div>
    @error('items')<div class="alert alert-danger">{{ $message }}</div>@enderror
    <form method="POST" action="{{ route('room-service.food.store') }}" class="sona-form">@csrf
        @forelse($categories as $category)<div class="mb-5"><h3 class="mb-4">{{ $category->name }}</h3><div class="row">@foreach($category->menuItems as $item)<div class="col-md-6 col-lg-4 mb-4"><div class="card menu-card">@if($item->image_path)<img src="{{ Storage::url($item->image_path) }}" alt="{{ $item->name }}">@else<div class="d-flex align-items-center justify-content-center bg-light" style="height:180px"><i class="fa fa-cutlery" style="font-size:42px;color:#dfa974"></i></div>@endif<div class="card-body p-4"><div class="d-flex justify-content-between align-items-start"><h4>{{ $item->name }}</h4><strong style="color:#dfa974">Rp{{ number_format((float)$item->price,0,',','.') }}</strong></div><p class="text-muted">{{ $item->description ?: 'Disiapkan segar untuk Anda.' }}</p>@if($item->preparation_minutes)<small class="text-muted"><i class="fa fa-clock-o"></i> ± {{ $item->preparation_minutes }} menit</small>@endif<div class="form-row mt-3"><div class="col-4"><label class="small">Jumlah</label><input type="number" min="0" max="20" name="items[{{ $item->id }}][quantity]" value="{{ old('items.'.$item->id.'.quantity', 0) }}" class="form-control quantity-control"></div><div class="col-8"><label class="small">Catatan item</label><input name="items[{{ $item->id }}][special_notes]" value="{{ old('items.'.$item->id.'.special_notes') }}" class="form-control" placeholder="Contoh: tidak pedas"></div></div></div></div></div>@endforeach</div></div>@empty<div class="alert alert-light border text-center py-5">Belum ada menu yang tersedia.</div>@endforelse
        @if($categories->isNotEmpty())<div class="auth-card"><label>Catatan pengantaran</label><textarea name="delivery_notes" rows="3" class="form-control" placeholder="Contoh: antar pukul 19.00, ketuk pintu dua kali">{{ old('delivery_notes') }}</textarea><div class="d-flex flex-wrap justify-content-between align-items-center mt-4"><p class="text-muted mb-2 mb-md-0"><i class="fa fa-file-text-o mr-1"></i>Pesanan akan masuk ke folio setelah diselesaikan Receptionist.</p><button class="sona-button" data-confirm="Pastikan jumlah dan catatan menu sudah benar." data-confirm-title="Kirim pesanan F&B?">Kirim Pesanan</button></div></div>@endif
    </form>
</div></section>
@endsection
