@php
    $rate = $rate ?? null;
    $selectedDays = old('days_of_week', $rate?->days_of_week ?? []);
    $dayNames = [1 => 'Senin', 2 => 'Selasa', 3 => 'Rabu', 4 => 'Kamis', 5 => 'Jumat', 6 => 'Sabtu', 7 => 'Minggu'];
@endphp
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Tipe kamar <span class="text-danger">*</span></label><select name="room_type_id" class="form-select @error('room_type_id') is-invalid @enderror" required><option value="">Pilih tipe kamar</option>@foreach($roomTypes as $roomType)<option value="{{ $roomType->id }}" @selected((string)old('room_type_id',$rate?->room_type_id)===(string)$roomType->id)>{{ $roomType->name }}</option>@endforeach</select>@error('room_type_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Nama aturan <span class="text-danger">*</span></label><input name="name" value="{{ old('name',$rate?->name) }}" class="form-control @error('name') is-invalid @enderror" placeholder="Weekend Rate" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Mulai berlaku</label><input type="date" name="start_date" value="{{ old('start_date',$rate?->start_date?->format('Y-m-d')) }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Selesai berlaku</label><input type="date" name="end_date" value="{{ old('end_date',$rate?->end_date?->format('Y-m-d')) }}" class="form-control @error('end_date') is-invalid @enderror">@error('end_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Prioritas</label><input type="number" min="0" name="priority" value="{{ old('priority',$rate?->priority ?? 0) }}" class="form-control"><small class="text-muted">Angka lebih tinggi dipilih lebih dulu.</small></div>
    <div class="col-md-6"><label class="form-label">Harga per malam <span class="text-danger">*</span></label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" name="price_per_night" value="{{ old('price_per_night',$rate?->price_per_night) }}" class="form-control @error('price_per_night') is-invalid @enderror" required></div>@error('price_per_night')<div class="text-danger fs-2 mt-1">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label d-block">Status</label><div class="form-check form-switch mt-2"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active',$rate?->is_active ?? true))><label class="form-check-label" for="is_active">Aturan harga aktif</label></div></div>
    <div class="col-12"><label class="form-label">Hari berlaku</label><div class="d-flex flex-wrap gap-2">@foreach($dayNames as $value=>$label)<div class="form-check border rounded p-3 ps-5"><input class="form-check-input" type="checkbox" name="days_of_week[]" value="{{ $value }}" id="day-{{ $value }}" @checked(in_array($value,$selectedDays))><label class="form-check-label" for="day-{{ $value }}">{{ $label }}</label></div>@endforeach</div><small class="text-muted">Kosongkan bila berlaku setiap hari.</small></div>
</div>
