@extends('layouts.main')
@section('title','Check-In '.$reservation->booking_code)
@section('content')
    <x-dashboard.page-heading :title="'Check-In '.$reservation->booking_code" :description="$reservation->guest_name.' · '.$reservation->roomType->name" :back="route('receptionist.reservations.show',$reservation)"/>
    <form method="POST" enctype="multipart/form-data" action="{{ route('receptionist.checkin.store',$reservation) }}" data-confirm="Pastikan identitas, nomor telepon, kamar, dan penyerahan kunci sudah benar." data-confirm-title="Konfirmasi check-in?">@csrf<div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><h5 class="fw-semibold mb-4">Verifikasi Tamu & Kamar</h5><div class="row g-3">
        <div class="col-md-6"><label class="form-label">Kamar fisik *</label><select name="room_id" class="form-select @error('room_id') is-invalid @enderror" required><option value="">Pilih kamar</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected(old('room_id',$reservation->room_id)==$room->id)>Kamar {{ $room->room_number }} · {{ $room->status->label() }}</option>@endforeach</select>@error('room_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Nomor telepon saat check-in *</label><input name="guest_phone" value="{{ old('guest_phone',$reservation->guest_phone) }}" class="form-control" required><small class="text-muted">Nomor ini digunakan untuk verifikasi QR room service.</small></div>
        <div class="col-md-4"><label class="form-label">Jenis identitas *</label><select name="identity_type" class="form-select" required>@foreach(['KTP','SIM','Passport','Other'] as $type)<option value="{{ $type }}" @selected(old('identity_type','KTP')===$type)>{{ $type }}</option>@endforeach</select></div><div class="col-md-4"><label class="form-label">Nomor identitas</label><input name="identity_number" value="{{ old('identity_number') }}" class="form-control"></div><div class="col-md-4"><label class="form-label">Foto identitas privat *</label><input type="file" name="identity_photo" accept="image/jpeg,image/png,image/webp" class="form-control @error('identity_photo') is-invalid @enderror" required>@error('identity_photo')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label">Kode/nomor kunci *</label><input name="key_code" value="{{ old('key_code') }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Security deposit</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" name="security_deposit_amount" value="{{ old('security_deposit_amount',0) }}" class="form-control"></div></div><div class="col-12"><label class="form-label">Catatan check-in</label><textarea name="notes" rows="3" class="form-control">{{ old('notes') }}</textarea></div>
    </div></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><h5 class="fw-semibold mb-3">Pembayaran / Deposit</h5><p>Total reservasi <strong class="d-block fs-5">Rp{{ number_format((float)$reservation->grand_total,0,',','.') }}</strong></p><p>Status pembayaran: <strong>{{ str($reservation->payment_status->value)->title() }}</strong></p><div class="mb-3"><label class="form-label">Nominal diterima</label><input type="number" min="0" name="payment_amount" value="{{ old('payment_amount',0) }}" class="form-control"></div><div class="mb-3"><label class="form-label">Metode</label><select name="payment_method_id" class="form-select"><option value="">Pilih bila ada pembayaran</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}">{{ $method->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Referensi</label><input name="reference_number" class="form-control"></div><div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="confirm_check_in" value="1" id="confirm" required><label class="form-check-label" for="confirm">Identitas diverifikasi dan kunci telah diserahkan.</label></div><button class="btn btn-primary w-100">Aktifkan Stay & Check-In</button></div></div></div></div></form>
@endsection
