@extends('layouts.main')
@section('title','Folio '.$folio->folio_number)
@section('content')
<x-dashboard.page-heading :title="'Folio '.$folio->folio_number" :description="$folio->stay->guest_name.' · Kamar '.$folio->stay->room->room_number" :back="route('receptionist.folios.index')"/>
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><h5 class="fw-semibold mb-4">Item Folio</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Waktu</th><th>Jenis</th><th>Deskripsi</th><th>Qty</th><th>Petugas</th><th class="text-end">Jumlah</th></tr></thead><tbody>
@forelse($folio->items as $item)
<tr class="{{ $item->is_void?'text-decoration-line-through text-muted':'' }}"><td>{{ $item->posted_at->format('d M H:i') }}</td><td><span class="badge bg-light-primary text-primary">{{ str($item->item_type)->title() }}</span></td><td>{{ $item->description }}</td><td>{{ (float)$item->quantity }}</td><td>{{ $item->postedBy?->name ?? 'Sistem' }}</td><td class="text-end fw-semibold">Rp{{ number_format((float)$item->amount,0,',','.') }}</td></tr>
@empty
<tr><td colspan="6" class="text-center text-muted py-5">Belum ada item folio.</td></tr>
@endforelse
</tbody></table></div></div></div><div class="card"><div class="card-body"><h5 class="fw-semibold mb-4">Riwayat Pembayaran</h5><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Kode</th><th>Waktu</th><th>Metode</th><th>Petugas</th><th>Status</th><th class="text-end">Nominal</th></tr></thead><tbody>
@forelse($folio->payments as $payment)
<tr><td><a href="{{ route('receptionist.payments.show',$payment) }}">{{ $payment->payment_code }}</a></td><td>{{ $payment->paid_at?->format('d M H:i') ?? $payment->created_at->format('d M H:i') }}</td><td>{{ $payment->method->name }}</td><td>{{ $payment->receivedBy?->name ?? 'Midtrans' }}</td><td><span class="badge bg-light-{{ $payment->status->badgeClass() }} text-{{ $payment->status->badgeClass() }}">{{ $payment->status->label() }}</span></td><td class="text-end">Rp{{ number_format((float)$payment->amount,0,',','.') }}</td></tr>
@empty
<tr><td colspan="6" class="text-center text-muted">Belum ada pembayaran.</td></tr>
@endforelse
</tbody></table></div></div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><span>Status</span><span class="badge {{ $folio->status==='open'?'bg-light-warning text-warning':'bg-light-success text-success' }}">{{ $folio->status==='open'?'Aktif':'Ditutup' }}</span></div><hr><div class="d-flex justify-content-between"><span>Total</span><strong>Rp{{ number_format((float)$folio->total_amount,0,',','.') }}</strong></div><div class="d-flex justify-content-between mt-2"><span>Dibayar</span><span class="text-success">Rp{{ number_format((float)$folio->paid_amount,0,',','.') }}</span></div><div class="d-flex justify-content-between mt-3 pt-3 border-top"><strong>Outstanding</strong><strong class="{{ (float)$folio->balance_amount>0?'text-danger':'text-success' }}">Rp{{ number_format((float)$folio->balance_amount,0,',','.') }}</strong></div></div></div>
@if($folio->status==='open' && (float)$folio->balance_amount>0)
<div class="card"><div class="card-body"><h5 class="fw-semibold mb-3">Catat Pembayaran</h5><form method="POST" action="{{ route('receptionist.folios.payments.store',$folio) }}" data-confirm="Pembayaran akan dicatat permanen pada histori transaksi." data-confirm-title="Konfirmasi pembayaran?">@csrf<div class="mb-3"><label class="form-label">Nominal *</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" name="payment_amount" min="1" max="{{ (int)$folio->balance_amount }}" value="{{ old('payment_amount',(int)$folio->balance_amount) }}" class="form-control @error('payment_amount') is-invalid @enderror" required>@error('payment_amount')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="mb-3"><label class="form-label">Metode *</label><select name="payment_method_id" class="form-select" required><option value="">Pilih metode</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected((string)old('payment_method_id')===(string)$method->id)>{{ $method->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Referensi</label><input name="reference_number" value="{{ old('reference_number') }}" class="form-control" placeholder="Opsional"></div><div class="mb-3"><label class="form-label">Catatan</label><textarea name="notes" rows="2" class="form-control">{{ old('notes') }}</textarea></div><button class="btn btn-primary w-100"><i class="ti ti-cash me-1"></i>Simpan Pembayaran</button></form></div></div>
@endif
</div></div>
@endsection
