@extends('layouts.main')
@section('title',$reservation->booking_code)
@section('content')
    <x-dashboard.page-heading :title="$reservation->booking_code" :description="$reservation->guest_name.' · '.($reservation->source==='walk_in'?'Walk-In':'Online')" :back="route('receptionist.reservations.index')">
        @if(in_array($reservation->status->value,['paid','confirmed']))<a href="{{ route('receptionist.checkin.create',$reservation) }}" class="btn btn-primary"><i class="ti ti-login me-1"></i>Proses Check-In</a>@elseif($reservation->stay?->status?->value==='active')<a href="{{ route('receptionist.checkout.create',$reservation->stay) }}" class="btn btn-warning"><i class="ti ti-logout me-1"></i>Proses Check-Out</a>@endif
    </x-dashboard.page-heading>
    <div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><div class="row g-3"><div class="col-md-6"><span class="text-muted">Tamu</span><h5>{{ $reservation->guest_name }}</h5><p>{{ $reservation->guest_phone }}<br>{{ $reservation->guest_email?:'-' }}</p></div><div class="col-md-6"><span class="text-muted">Kamar</span><h5>{{ $reservation->roomType->name }}</h5><p>{{ $reservation->room?'Kamar '.$reservation->room->room_number:'Belum ditentukan' }}</p></div><div class="col-md-4"><small class="text-muted">Check-In</small><strong class="d-block">{{ $reservation->check_in_date->translatedFormat('d F Y') }}</strong></div><div class="col-md-4"><small class="text-muted">Check-Out</small><strong class="d-block">{{ $reservation->check_out_date->translatedFormat('d F Y') }}</strong></div><div class="col-md-4"><small class="text-muted">Tamu</small><strong class="d-block">{{ $reservation->adults }} dewasa, {{ $reservation->children }} anak</strong></div></div>@if($reservation->stay)<hr><div class="alert alert-light-primary text-primary mb-0"><strong>Stay #{{ $reservation->stay->id }}</strong> · {{ str($reservation->stay->status->value)->title() }} · Check-in {{ $reservation->stay->check_in_at?->format('d M Y H:i') }}@if($reservation->stay->identity_photo_path)<a href="{{ route('receptionist.stays.identity',$reservation->stay) }}" class="float-end">Lihat Identitas Privat</a>@endif</div>@endif</div></div>
        <div class="card"><div class="card-body"><h5 class="fw-semibold mb-3">Pembayaran</h5><div class="table-responsive"><table class="table"><thead><tr><th>Kode</th><th>Metode</th><th>Status</th><th>Nominal</th><th>Waktu</th></tr></thead><tbody>@forelse($reservation->payments as $payment)<tr><td>{{ $payment->payment_code }}</td><td>{{ $payment->method->name }}</td><td>{{ $payment->status->value }}</td><td>Rp{{ number_format((float)$payment->amount,0,',','.') }}</td><td>{{ $payment->paid_at?->format('d M Y H:i')?:'-' }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></div></div>
    </div><div class="col-lg-4"><div class="card"><div class="card-body"><div class="d-flex justify-content-between"><span>Status</span><span class="badge bg-light-primary text-primary">{{ str($reservation->status->value)->replace('_',' ')->title() }}</span></div><hr><div class="d-flex justify-content-between"><span>Subtotal</span><span>Rp{{ number_format((float)$reservation->subtotal,0,',','.') }}</span></div><div class="d-flex justify-content-between text-success"><span>Diskon</span><span>-Rp{{ number_format((float)$reservation->discount_amount,0,',','.') }}</span></div><hr><div class="d-flex justify-content-between"><strong>Total</strong><strong>Rp{{ number_format((float)$reservation->grand_total,0,',','.') }}</strong></div><p class="mt-3 mb-0">Pembayaran: <strong>{{ str($reservation->payment_status->value)->title() }}</strong></p>@if($reservation->stay?->folio)<a href="{{ route('receptionist.folios.show',$reservation->stay->folio) }}" class="btn btn-outline-primary w-100 mt-4"><i class="ti ti-receipt me-1"></i>Buka Folio</a>@endif</div></div></div></div>
@endsection
