@extends('layouts.main')
@section('title','Reservasi Walk-In')
@section('content')
    <x-dashboard.page-heading title="Reservasi Walk-In" description="Daftarkan tamu yang datang langsung dan catat pembayaran awal bila ada." :back="route('receptionist.reservations.index')"/>
    <form method="POST" action="{{ route('receptionist.reservations.walk-in.store') }}">@csrf<div class="row"><div class="col-lg-8"><div class="card"><div class="card-body"><h5 class="fw-semibold mb-4">Data Tamu & Kamar</h5><div class="row g-3">
        <div class="col-md-6"><label class="form-label">Nama tamu *</label><input name="guest_name" value="{{ old('guest_name') }}" class="form-control @error('guest_name') is-invalid @enderror" required>@error('guest_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Nomor telepon *</label><input name="guest_phone" value="{{ old('guest_phone') }}" class="form-control @error('guest_phone') is-invalid @enderror" required>@error('guest_phone')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-12"><label class="form-label">Email</label><input type="email" name="guest_email" value="{{ old('guest_email') }}" class="form-control"></div>
        <div class="col-md-6"><label class="form-label">Check-In *</label><input type="date" name="check_in" min="{{ today()->format('Y-m-d') }}" value="{{ old('check_in',today()->format('Y-m-d')) }}" class="form-control" required></div><div class="col-md-6"><label class="form-label">Check-Out *</label><input type="date" name="check_out" min="{{ today()->addDay()->format('Y-m-d') }}" value="{{ old('check_out',today()->addDay()->format('Y-m-d')) }}" class="form-control @error('check_out') is-invalid @enderror" required>@error('check_out')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
        <div class="col-md-6"><label class="form-label">Kamar fisik *</label><select name="room_id" class="form-select @error('room_id') is-invalid @enderror" required><option value="">Pilih kamar</option>@foreach($rooms as $room)<option value="{{ $room->id }}" @selected(old('room_id')==$room->id)>Kamar {{ $room->room_number }} · {{ $room->roomType->name }} · {{ $room->status->label() }}</option>@endforeach</select>@error('room_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-2"><label class="form-label">Dewasa</label><input type="number" name="adults" min="1" value="{{ old('adults',1) }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Anak</label><input type="number" name="children" min="0" value="{{ old('children',0) }}" class="form-control" required></div><div class="col-md-2"><label class="form-label">Promo</label><input name="promo_code" value="{{ old('promo_code') }}" class="form-control"></div><div class="col-12"><label class="form-label">Permintaan khusus</label><textarea name="special_requests" rows="3" class="form-control">{{ old('special_requests') }}</textarea></div>
    </div></div></div></div><div class="col-lg-4"><div class="card"><div class="card-body"><h5 class="fw-semibold mb-4">Pembayaran Awal</h5><div class="mb-3"><label class="form-label">Nominal</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" name="payment_amount" value="{{ old('payment_amount',0) }}" class="form-control"></div></div><div class="mb-3"><label class="form-label">Metode</label><select name="payment_method_id" class="form-select"><option value="">Pilih bila ada pembayaran</option>@foreach($paymentMethods as $method)<option value="{{ $method->id }}" @selected(old('payment_method_id')==$method->id)>{{ $method->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label">Nomor referensi</label><input name="reference_number" value="{{ old('reference_number') }}" class="form-control"></div><button class="btn btn-primary w-100"><i class="ti ti-device-floppy me-1"></i>Buat Reservasi</button></div></div></div></div></form>
@endsection
