@extends('layouts.guest')
@section('title','Konfirmasi Reservasi · Candra Resort')
@section('content')
    <section class="page-hero" style="background-image:url('{{ asset('landing-lage/img/hero/hero-2.jpg') }}')"><div class="container text-center"><h1>Konfirmasi Reservasi</h1><p>Periksa detail sebelum menahan kamar Anda.</p></div></section>
    <section class="spad" style="background:#f8f8f8"><div class="container"><form method="POST" action="{{ route('guest.reservations.store') }}">@csrf<input type="hidden" name="room_type_id" value="{{ $roomType->id }}"><input type="hidden" name="check_in" value="{{ $validated['check_in'] }}"><input type="hidden" name="check_out" value="{{ $validated['check_out'] }}"><input type="hidden" name="adults" value="{{ $validated['adults'] }}"><input type="hidden" name="children" value="{{ $validated['children']??0 }}"><input type="hidden" name="promo_code" value="{{ $validated['promo_code']??'' }}">
        <div class="row"><div class="col-lg-8"><div class="auth-card mb-4"><h3 class="mb-4">Detail Menginap</h3><div class="row"><div class="col-md-5">@php($image=$roomType->images->first()?->image_path)<img src="{{ $image?asset('storage/'.$image):asset('landing-lage/img/room/room-details.jpg') }}" class="w-100 mb-3" alt="{{ $roomType->name }}"></div><div class="col-md-7"><h4>{{ $roomType->name }}</h4><p class="text-muted">{{ Str::limit($roomType->description,160) }}</p><div class="row"><div class="col-6"><small class="text-muted">Check-In</small><strong class="d-block">{{ Carbon\Carbon::parse($validated['check_in'])->translatedFormat('d F Y') }}</strong></div><div class="col-6"><small class="text-muted">Check-Out</small><strong class="d-block">{{ Carbon\Carbon::parse($validated['check_out'])->translatedFormat('d F Y') }}</strong></div></div><hr><p class="mb-1">{{ $validated['adults'] }} dewasa, {{ $validated['children']??0 }} anak</p><p>{{ $quote['total_nights'] }} malam</p></div></div></div>
        <div class="auth-card mb-4"><h3 class="mb-4">Data Tamu</h3><div class="row"><div class="col-md-6 mb-3"><small class="text-muted">Nama</small><strong class="d-block">{{ auth()->user()->name }}</strong></div><div class="col-md-6 mb-3"><small class="text-muted">Email</small><strong class="d-block">{{ auth()->user()->email }}</strong></div><div class="col-md-6"><small class="text-muted">Nomor telepon</small><strong class="d-block">{{ auth()->user()->phone }}</strong></div></div><hr><label>Permintaan khusus</label><textarea name="special_requests" rows="4" class="form-control" placeholder="Contoh: kamar jauh dari lift, perkiraan tiba pukul 15.00">{{ old('special_requests') }}</textarea></div>
        </div><div class="col-lg-4"><div class="auth-card"><h3 class="mb-4">Ringkasan Harga</h3>@foreach($quote['nights'] as $night)<div class="d-flex justify-content-between mb-2"><span>{{ Carbon\Carbon::parse($night['stay_date'])->translatedFormat('d M') }}<small class="d-block text-muted">{{ $night['rate_name'] }}</small></span><strong>Rp{{ number_format($night['price_before_discount'],0,',','.') }}</strong></div>@endforeach<hr><div class="d-flex justify-content-between"><span>Subtotal</span><span>Rp{{ number_format($quote['subtotal'],0,',','.') }}</span></div>@if($quote['discount_amount']>0)<div class="d-flex justify-content-between text-success"><span>Diskon {{ $quote['promotion']->code }}</span><span>-Rp{{ number_format($quote['discount_amount'],0,',','.') }}</span></div>@endif<hr><div class="d-flex justify-content-between mb-4"><strong>Total</strong><strong style="color:#dfa974;font-size:20px">Rp{{ number_format($quote['grand_total'],0,',','.') }}</strong></div><div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="terms" value="1" id="terms" required><label class="form-check-label" for="terms">Saya menyetujui kebijakan hotel dan batas waktu pembayaran.</label></div><button class="sona-button w-100">Buat Reservasi</button><p class="small text-muted mt-3 mb-0">Kamar ditahan selama {{ config('services.midtrans.payment_expiry_minutes',30) }} menit setelah reservasi dibuat.</p></div></div></div>
    </form></div></section>
@endsection
