@php($room = $room ?? null)
<div class="row g-3">
    <div class="col-md-6"><label class="form-label">Tipe kamar <span class="text-danger">*</span></label><select name="room_type_id" class="form-select @error('room_type_id') is-invalid @enderror" required><option value="">Pilih tipe kamar</option>@foreach($roomTypes as $roomType)<option value="{{ $roomType->id }}" @selected((string)old('room_type_id', $room?->room_type_id) === (string)$roomType->id)>{{ $roomType->code }} · {{ $roomType->name }}</option>@endforeach</select>@error('room_type_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Nomor kamar <span class="text-danger">*</span></label><input name="room_number" value="{{ old('room_number', $room?->room_number) }}" class="form-control @error('room_number') is-invalid @enderror" placeholder="201" required>@error('room_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-3"><label class="form-label">Lantai</label><input name="floor" value="{{ old('floor', $room?->floor) }}" class="form-control" placeholder="2"></div>
    <div class="col-md-6"><label class="form-label">Status operasional <span class="text-danger">*</span></label><select name="status" class="form-select @error('status') is-invalid @enderror" required>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(old('status', $room?->status?->value ?? 'available') === $status->value)>{{ $status->label() }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label">Alasan perubahan status</label><input name="status_reason" value="{{ old('status_reason') }}" class="form-control" placeholder="Wajib dijelaskan untuk perubahan operasional"></div>
    <div class="col-12"><label class="form-label">Catatan kamar</label><textarea name="notes" rows="4" class="form-control">{{ old('notes', $room?->notes) }}</textarea></div>
    <div class="col-12"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active', $room?->is_active ?? true))><label class="form-check-label" for="is_active">Kamar aktif dan dapat dioperasikan</label></div></div>
    @unless($room)<div class="col-12"><div class="alert alert-light-primary text-primary mb-0"><i class="ti ti-qrcode me-2"></i>Token QR unik akan dibuat otomatis setelah kamar disimpan. Receptionist tidak perlu mengisinya.</div></div>@endunless
</div>
