@extends('layouts.main')
@section('title', 'Kamar & QR')
@section('content')
    <x-dashboard.page-heading title="Kamar & QR" description="Kelola unit fisik, status operasional, dan QR permanen setiap kamar."><a href="{{ route('receptionist.rooms.create') }}" class="btn btn-primary"><i class="ti ti-plus me-1"></i>Tambah Kamar</a></x-dashboard.page-heading>
    <div class="card"><div class="card-body">
        <form method="GET" class="row g-2 mb-4"><div class="col-lg-4"><input type="search" name="search" value="{{ request('search') }}" class="form-control" placeholder="Cari nomor kamar..."></div><div class="col-lg-3"><select name="room_type_id" class="form-select"><option value="">Semua tipe kamar</option>@foreach($roomTypes as $roomType)<option value="{{ $roomType->id }}" @selected((string)request('room_type_id') === (string)$roomType->id)>{{ $roomType->name }}</option>@endforeach</select></div><div class="col-lg-3"><select name="status" class="form-select"><option value="">Semua status</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ $status->label() }}</option>@endforeach</select></div><div class="col-lg-2 d-flex gap-2"><button class="btn btn-outline-primary flex-grow-1">Filter</button><a href="{{ route('receptionist.rooms.index') }}" class="btn btn-outline-secondary"><i class="ti ti-refresh"></i></a></div></form>
        <div class="table-responsive"><table class="table align-middle text-nowrap"><thead><tr><th>Nomor</th><th>Tipe Kamar</th><th>Lantai</th><th>Status</th><th>QR</th><th>Aktif</th><th class="text-end">Aksi</th></tr></thead><tbody>
            @forelse($rooms as $room)
                @php($color = match($room->status->value) {'available'=>'success','reserved'=>'primary','occupied'=>'secondary','cleaning'=>'info','maintenance'=>'warning',default=>'danger'})
                <tr><td><a class="fw-semibold text-dark" href="{{ route('receptionist.rooms.show', $room) }}">Kamar {{ $room->room_number }}</a></td><td>{{ $room->roomType->name }}</td><td>{{ $room->floor ?: '-' }}</td><td><span class="badge bg-light-{{ $color }} text-{{ $color }}">{{ $room->status->label() }}</span></td><td><a href="{{ route('receptionist.rooms.qr', $room) }}" class="btn btn-sm btn-light-primary text-primary"><i class="ti ti-qrcode me-1"></i>Lihat</a></td><td><span class="badge {{ $room->is_active ? 'bg-light-success text-success' : 'bg-light-danger text-danger' }}">{{ $room->is_active ? 'Ya' : 'Tidak' }}</span></td><td><div class="d-flex justify-content-end gap-2"><a href="{{ route('receptionist.rooms.show', $room) }}" class="btn btn-sm btn-outline-secondary"><i class="ti ti-eye"></i></a><a href="{{ route('receptionist.rooms.edit', $room) }}" class="btn btn-sm btn-outline-primary"><i class="ti ti-edit"></i></a><form method="POST" action="{{ route('receptionist.rooms.destroy', $room) }}" data-confirm="Kamar dengan riwayat transaksi akan dinonaktifkan, bukan dihapus permanen." data-confirm-title="Hapus kamar?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="ti ti-trash"></i></button></form></div></td></tr>
            @empty<tr><td colspan="7" class="text-center text-muted py-5"><i class="ti ti-door fs-8 d-block mb-2"></i>Belum ada kamar.</td></tr>@endforelse
        </tbody></table></div>{{ $rooms->links() }}
    </div></div>
@endsection
