@extends('layouts.guest')
@section('title', $roomType->name.' · Candra Resort')
@section('content')
    <section class="page-hero" style="background-image:url('{{ asset('landing-lage/img/hero/hero-2.jpg') }}')"><div class="container text-center"><h1>{{ $roomType->name }}</h1><p>Kenyamanan yang dirancang untuk Anda.</p></div></section>
    <section class="room-details-section room-details-spaced"><div class="container"><div class="row"><div class="col-lg-8"><div class="room-details-item">
        @php($mainImage=$roomType->images->first()?->image_path ? asset('storage/'.$roomType->images->first()->image_path) : asset('landing-lage/img/room/room-details.jpg'))
        <img src="{{ $mainImage }}" alt="{{ $roomType->name }}"><div class="rd-text"><div class="rd-title"><h3>{{ $roomType->name }}</h3></div><h2>Rp{{ number_format((float)$roomType->base_price,0,',','.') }}<span>/malam</span></h2><table><tbody><tr><td class="r-o">Ukuran:</td><td>{{ $roomType->room_size_sqm ? $roomType->room_size_sqm.' m²':'-' }}</td></tr><tr><td class="r-o">Kapasitas:</td><td>{{ $roomType->capacity }} tamu ({{ $roomType->max_adults }} dewasa, {{ $roomType->max_children }} anak)</td></tr><tr><td class="r-o">Tempat Tidur:</td><td>{{ $roomType->bed_count }} {{ $roomType->bed_type }}</td></tr><tr><td class="r-o">Sarapan:</td><td>{{ $roomType->breakfast_included?'Termasuk':'Tidak termasuk' }}</td></tr><tr><td class="r-o">Fasilitas:</td><td>{{ $roomType->facilities->pluck('name')->join(', ')?:'-' }}</td></tr></tbody></table><p>{{ $roomType->description ?: 'Nikmati kamar nyaman dengan fasilitas yang disiapkan untuk pengalaman menginap terbaik di Candra Resort.' }}</p></div>
        @if($roomType->images->count()>1)<div class="row mt-4">@foreach($roomType->images->skip(1) as $image)<div class="col-md-4 mb-3"><img src="{{ asset('storage/'.$image->image_path) }}" class="w-100" style="height:140px;object-fit:cover" alt="{{ $image->alt_text }}"></div>@endforeach</div>@endif
    </div></div><div class="col-lg-4"><div class="room-booking"><h3>Cek & Pesan</h3><form action="{{ route('public.rooms.show',$roomType) }}" method="GET">
        <div class="check-date"><label for="check_in">Check-In</label><input type="date" id="check_in" name="check_in" min="{{ today()->format('Y-m-d') }}" value="{{ old('check_in',$search['check_in'] ?? today()->addDay()->format('Y-m-d')) }}" required></div>
        <div class="check-date"><label for="check_out">Check-Out</label><input type="date" id="check_out" name="check_out" min="{{ today()->addDay()->format('Y-m-d') }}" value="{{ old('check_out',$search['check_out'] ?? today()->addDays(2)->format('Y-m-d')) }}" required></div>
        <div class="select-option"><label for="adults">Dewasa</label><select id="adults" name="adults">@for($i=1;$i<=$roomType->max_adults;$i++)<option value="{{ $i }}" @selected(($search['adults']??1)==$i)>{{ $i }} Dewasa</option>@endfor</select></div>
        @if($roomType->max_children>0)<div class="select-option"><label for="children">Anak</label><select id="children" name="children">@for($i=0;$i<=$roomType->max_children;$i++)<option value="{{ $i }}" @selected(($search['children']??0)==$i)>{{ $i }} Anak</option>@endfor</select></div>@else<input type="hidden" name="children" value="0">@endif
        <div class="check-date"><label for="promo_code">Kode Promosi</label><input type="text" id="promo_code" name="promo_code" value="{{ old('promo_code',$search['promo_code']??'') }}" placeholder="Opsional"></div><button type="submit">Cek Ketersediaan</button>
    </form>
    @if($search)<div class="mt-4 p-3" style="background:#f8f8f8">@if($availableRooms>0)<p class="text-success font-weight-bold">{{ $availableRooms }} kamar tersedia</p><div class="d-flex justify-content-between"><span>{{ $quote['total_nights'] }} malam</span><strong>Rp{{ number_format($quote['subtotal'],0,',','.') }}</strong></div>@if($quote['discount_amount']>0)<div class="d-flex justify-content-between text-success"><span>Diskon</span><strong>-Rp{{ number_format($quote['discount_amount'],0,',','.') }}</strong></div>@endif<hr><div class="d-flex justify-content-between mb-3"><span>Total</span><strong>Rp{{ number_format($quote['grand_total'],0,',','.') }}</strong></div><a class="sona-button d-block text-center" href="{{ route('guest.reservations.create',['roomType'=>$roomType]+$search) }}">Lanjut Pesan</a>@else<p class="text-danger mb-0">Kamar tidak tersedia pada tanggal tersebut.</p>@endif</div>@endif
    </div></div></div></div></section>
@endsection
