@php
    $roomType = $roomType ?? null;
    $selectedFacilities = old('facilities', $roomType ? $roomType->facilities->pluck('id')->all() : []);
@endphp
<div class="row g-3">
    <div class="col-md-3"><label class="form-label">Kode <span class="text-danger">*</span></label><input name="code" value="{{ old('code', $roomType?->code) }}" class="form-control @error('code') is-invalid @enderror" placeholder="DLX" required>@error('code')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-5"><label class="form-label">Nama tipe kamar <span class="text-danger">*</span></label><input name="name" value="{{ old('name', $roomType?->name) }}" class="form-control @error('name') is-invalid @enderror" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label">Slug</label><input name="slug" value="{{ old('slug', $roomType?->slug) }}" class="form-control @error('slug') is-invalid @enderror" placeholder="Otomatis dari nama">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label">Deskripsi lengkap</label><textarea name="description" rows="5" class="form-control @error('description') is-invalid @enderror">{{ old('description', $roomType?->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4 col-lg-2"><label class="form-label">Kapasitas</label><input type="number" min="1" name="capacity" value="{{ old('capacity', $roomType?->capacity ?? 2) }}" class="form-control" required></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">Maks. dewasa</label><input type="number" min="1" name="max_adults" value="{{ old('max_adults', $roomType?->max_adults ?? 2) }}" class="form-control" required></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">Maks. anak</label><input type="number" min="0" name="max_children" value="{{ old('max_children', $roomType?->max_children ?? 0) }}" class="form-control" required></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">Jenis kasur</label><input name="bed_type" value="{{ old('bed_type', $roomType?->bed_type) }}" class="form-control" placeholder="King"></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">Jumlah kasur</label><input type="number" min="1" name="bed_count" value="{{ old('bed_count', $roomType?->bed_count ?? 1) }}" class="form-control" required></div>
    <div class="col-md-4 col-lg-2"><label class="form-label">Luas (m²)</label><input type="number" min="0" step="0.01" name="room_size_sqm" value="{{ old('room_size_sqm', $roomType?->room_size_sqm) }}" class="form-control"></div>
    <div class="col-md-4"><label class="form-label">Harga dasar / malam <span class="text-danger">*</span></label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" name="base_price" value="{{ old('base_price', $roomType?->base_price ?? 0) }}" class="form-control @error('base_price') is-invalid @enderror" required></div></div>
    <div class="col-md-4"><label class="form-label">Harga extra bed</label><div class="input-group"><span class="input-group-text">Rp</span><input type="number" min="0" name="extra_bed_price" value="{{ old('extra_bed_price', $roomType?->extra_bed_price ?? 0) }}" class="form-control"></div></div>
    <div class="col-md-4"><label class="form-label">Urutan tampil</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order', $roomType?->sort_order ?? 0) }}" class="form-control"></div>
    <div class="col-12"><label class="form-label">Fasilitas kamar</label><div class="row g-2">@forelse($facilities as $facility)<div class="col-md-4 col-lg-3"><div class="form-check border rounded p-3 ps-5"><input class="form-check-input" type="checkbox" name="facilities[]" value="{{ $facility->id }}" id="facility-{{ $facility->id }}" @checked(in_array($facility->id, $selectedFacilities))><label class="form-check-label" for="facility-{{ $facility->id }}"><i class="ti {{ $facility->icon ?: 'ti-check' }} me-1"></i>{{ $facility->name }}</label></div></div>@empty<div class="col-12 text-muted">Belum ada fasilitas kamar aktif.</div>@endforelse</div></div>
    <div class="col-12"><label class="form-label">Foto kamar</label><input type="file" name="images[]" multiple accept="image/jpeg,image/png,image/webp" class="form-control @error('images.*') is-invalid @enderror"><small class="text-muted">Maksimal 10 foto sekali unggah, masing-masing 4 MB (JPG, PNG, atau WebP).</small>@error('images.*')<div class="invalid-feedback d-block">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><div class="form-check form-switch"><input type="hidden" name="breakfast_included" value="0"><input class="form-check-input" type="checkbox" name="breakfast_included" value="1" id="breakfast_included" @checked(old('breakfast_included', $roomType?->breakfast_included ?? false))><label class="form-check-label" for="breakfast_included">Sarapan termasuk</label></div></div>
    <div class="col-md-6"><div class="form-check form-switch"><input type="hidden" name="is_active" value="0"><input class="form-check-input" type="checkbox" name="is_active" value="1" id="is_active" @checked(old('is_active', $roomType?->is_active ?? true))><label class="form-check-label" for="is_active">Tipe kamar aktif</label></div></div>
</div>
