@extends('layouts.main')
@section('title', $roomType->name)
@section('content')
    <x-dashboard.page-heading :title="$roomType->name" :description="$roomType->code.' · Detail tipe kamar'" :back="route('receptionist.room-types.index')">
        <a href="{{ route('public.rooms.show', $roomType) }}" target="_blank" class="btn btn-outline-secondary"><i class="ti ti-external-link me-1"></i>Lihat Publik</a><a href="{{ route('receptionist.room-types.edit', $roomType) }}" class="btn btn-primary"><i class="ti ti-edit me-1"></i>Edit</a>
    </x-dashboard.page-heading>
    <div class="row"><div class="col-lg-8">
        <div class="card"><div class="card-body"><div class="row g-3">@forelse($roomType->images as $image)<div class="{{ $loop->first ? 'col-12' : 'col-md-4' }}"><img src="{{ asset('storage/'.$image->image_path) }}" class="w-100 rounded object-fit-cover" style="height:{{ $loop->first ? '360' : '140' }}px" alt="{{ $image->alt_text }}"></div>@empty<div class="col-12 bg-light rounded d-flex align-items-center justify-content-center text-muted" style="height:300px"><div class="text-center"><i class="ti ti-photo fs-10"></i><p>Belum ada foto</p></div></div>@endforelse</div></div></div>
        <div class="card"><div class="card-body"><h5 class="fw-semibold">Deskripsi</h5><p class="text-muted mb-4">{{ $roomType->description ?: 'Belum ada deskripsi.' }}</p><h5 class="fw-semibold">Fasilitas</h5><div class="d-flex flex-wrap gap-2">@forelse($roomType->facilities as $facility)<span class="badge bg-light-primary text-primary p-2"><i class="ti {{ $facility->icon ?: 'ti-check' }} me-1"></i>{{ $facility->name }}</span>@empty<span class="text-muted">Belum ada fasilitas.</span>@endforelse</div></div></div>
    </div><div class="col-lg-4">
        <div class="card"><div class="card-body"><div class="d-flex justify-content-between mb-3"><span>Status</span><span class="badge {{ $roomType->is_active ? 'bg-light-success text-success' : 'bg-light-danger text-danger' }}">{{ $roomType->is_active ? 'Aktif' : 'Nonaktif' }}</span></div><h3 class="fw-semibold text-primary">Rp{{ number_format((float)$roomType->base_price,0,',','.') }}<small class="fs-3 text-muted"> / malam</small></h3><hr><dl class="row mb-0"><dt class="col-6">Kapasitas</dt><dd class="col-6 text-end">{{ $roomType->capacity }} tamu</dd><dt class="col-6">Dewasa / anak</dt><dd class="col-6 text-end">{{ $roomType->max_adults }} / {{ $roomType->max_children }}</dd><dt class="col-6">Kasur</dt><dd class="col-6 text-end">{{ $roomType->bed_count }} {{ $roomType->bed_type }}</dd><dt class="col-6">Luas</dt><dd class="col-6 text-end">{{ $roomType->room_size_sqm ?: '-' }} m²</dd><dt class="col-6">Sarapan</dt><dd class="col-6 text-end">{{ $roomType->breakfast_included ? 'Termasuk' : 'Tidak' }}</dd><dt class="col-6">Unit kamar</dt><dd class="col-6 text-end">{{ $roomType->rooms_count }}</dd><dt class="col-6">Reservasi</dt><dd class="col-6 text-end">{{ $roomType->reservations_count }}</dd></dl></div></div>
    </div></div>
@endsection
